version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: reserva  # Nome do banco de dados
      POSTGRES_USER: postgres    # Nome do usuário
      POSTGRES_PASSWORD: postgres  # Senha do usuário
    ports:
      - "5430:5430"  # Mapeamento da porta do host para a porta do container
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - 5430